### ISSUE TITLE
Roadmap towards Paris meeting (2022-09-20)

### ISSUE THREAD

**Issue by raphaelfournier** [polifonia-project/facets-search-engine#41]
The FACETS pilot should have a *working* demo in Paris, during the 4-day meeting (starting 2022-09-20).
It should implement most of the features already in the Neuma search engine.

# Data loading
- [x] Precise the list of supported score formats
- [x] Make sure that one of each can be indexed

# Interfaces
We want:
- fully working REST interface, demo with curl.
- fully working GUI interface
- easily accessible demo

## REST-curl interface
- [x] #40 
- [x] Check that everything works

## GUI
- [x] The "loading data" module *is* important, but developing it in more details is probably not a priority now
- [ ] a MIDI module to listen to a score would be a plus. Not a top priority, but easily taken from Neuma, probably.

### Search
- [x] #42
- [x] #44
- [x] #43
- [x] #45

The lyrics search (working w/ musicxml) should not be ported to other formats for now, it's not a priority.

### Dashboard
Enable better corpus/index navigation:
- [x] Score display
- [x] Paginate 

## Packaging
We want a dockerized version of the Neuma search engine. A new user should be given a very short list of commands (ideally, only one or two `docker run ...`), and be ready to test the search engine on given scores (*i.e.,* in a browser), with the possibility to add her own.

We need:
- [ ] #48
- [x] #47
- [x] #46
